export {
  GAME_STATES,
  FPS,
  STEP,
  FRAME_DIVIDER,
  PUB_SUB,
  ASSET_TYPES,
  GAME_WIDTH,
  GAME_HEIGHT,
  STATIC_TILE_WIDTH,
  STATIC_TILE_HEIGHT,
  MAX_ALLOWED_UPDATES_PER_STEP
} from './consts'
